# Interpreter-only DeSmuME source set for the LibXenon build.
# Paths are relative to desmume/src at the revision in upstream.lock.

DESMUME_CPP_SOURCES := \
	armcpu.cpp \
	arm_instructions.cpp \
	bios.cpp \
	cp15.cpp \
	commandline.cpp \
	common.cpp \
	debug.cpp \
	driver.cpp \
	Database.cpp \
	emufile.cpp \
	encrypt.cpp \
	FIFO.cpp \
	firmware.cpp \
	GPU.cpp \
	mc.cpp \
	path.cpp \
	readwrite.cpp \
	wifi.cpp \
	mic.cpp \
	MMU.cpp \
	NDSSystem.cpp \
	ROMReader.cpp \
	render3D.cpp \
	rtc.cpp \
	saves.cpp \
	slot1.cpp \
	slot2.cpp \
	SPU.cpp \
	matrix.cpp \
	gfx3d.cpp \
	thumb_instructions.cpp \
	movie.cpp \
	cheatSystem.cpp \
	texcache.cpp \
	rasterize.cpp \
	version.cpp \
	frontend/modules/Disassembler.cpp \
	utils/advanscene.cpp \
	utils/datetime.cpp \
	utils/guid.cpp \
	utils/emufat.cpp \
	utils/fsnitro.cpp \
	utils/xstring.cpp \
	utils/decrypt/crc.cpp \
	utils/decrypt/decrypt.cpp \
	utils/decrypt/header.cpp \
	utils/task.cpp \
	utils/vfat.cpp \
	utils/dlditool.cpp \
	utils/libfat/cache.cpp \
	utils/libfat/directory.cpp \
	utils/libfat/disc.cpp \
	utils/libfat/fatdir.cpp \
	utils/libfat/fatfile.cpp \
	utils/libfat/filetime.cpp \
	utils/libfat/file_allocation_table.cpp \
	utils/libfat/libfat.cpp \
	utils/libfat/libfat_public_api.cpp \
	utils/libfat/lock.cpp \
	utils/libfat/partition.cpp \
	utils/tinyxml/tinystr.cpp \
	utils/tinyxml/tinyxml.cpp \
	utils/tinyxml/tinyxmlerror.cpp \
	utils/tinyxml/tinyxmlparser.cpp \
	utils/colorspacehandler/colorspacehandler.cpp \
	addons/slot2_auto.cpp \
	addons/slot2_mpcf.cpp \
	addons/slot2_paddle.cpp \
	addons/slot2_gbagame.cpp \
	addons/slot2_none.cpp \
	addons/slot2_rumblepak.cpp \
	addons/slot2_guitarGrip.cpp \
	addons/slot2_hcv1000.cpp \
	addons/slot2_expMemory.cpp \
	addons/slot2_piano.cpp \
	addons/slot2_passme.cpp \
	addons/slot1_none.cpp \
	addons/slot1_r4.cpp \
	addons/slot1_retail_nand.cpp \
	addons/slot1_retail_auto.cpp \
	addons/slot1_retail_mcrom.cpp \
	addons/slot1_retail_mcrom_debug.cpp \
	addons/slot1comp_mc.cpp \
	addons/slot1comp_rom.cpp \
	addons/slot1comp_protocol.cpp \
	metaspu/metaspu.cpp \
	filter/deposterize.cpp \
	filter/xbrz.cpp

DESMUME_C_SOURCES := \
	libretro-common/compat/compat_getopt.c \
	libretro-common/file/file_path.c \
	libretro-common/compat/compat_strl.c \
	libretro-common/features/features_cpu.c \
	libretro-common/file/retro_dirent.c \
	libretro-common/file/retro_stat.c \
	libretro-common/encodings/encoding_utf.c
